Revert "Merge branch 'feat-QC' of https://github.com/Serendipity2-0/TradeManV1 into feat-QC"
This reverts commit 38d53a2f6719aa5a6ddecf6c37c7bc18774fa812, reversing
changes made to ad935c5c5901ebf5b76b9596a97b15a0ceb19cd2.

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -15,25 +15,56 @@ jobs:
       with:
         python-version: '3.11'
 
-    - name: Decode and save Firebase credentials
-      run: |
-        echo ${{ secrets.FIREBASE_CRED_PATH }} | base64 -d > $GITHUB_WORKSPACE/firebase_credentials.json
-      shell: bash
-
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
-        pip install firebase-admin
+        pip install -r requirements.txt
 
-    - name: Set environment variables
+    - name: Set up Firebase credentials
+      # Write the JSON content from the secret to a file
+      run: echo "${{ secrets.FIREBASE_CRED_PATH }}" > firebase-service-account.json
+      shell: bash
+
+    - name: Export Firebase environment variables
+      # Set the environment variables for the database URL and credentials path
       run: |
-        echo "FIREBASE_CRED_PATH=$GITHUB_WORKSPACE/firebase_credentials.json" >> $GITHUB_ENV
+        echo "FIREBASE_CRED_PATH=$(pwd)/firebase-service-account.json" >> $GITHUB_ENV
         echo "FIREBASE_DATABASE_URL=${{ secrets.FIREBASE_DATABASE_URL }}" >> $GITHUB_ENV
+      shell: bash
 
-    - name: Run Firebase script
+    - name: Verify Firebase credentials
+      run: |
+        if [ -f "$FIREBASE_CRED_PATH" ]; then
+          echo "Firebase credentials file found at $FIREBASE_CRED_PATH"
+          cat $FIREBASE_CRED_PATH
+        else
+          echo "Firebase credentials file not found."
+          exit 1
+        fi
+      shell: bash
+
+    - name: Check formatting with black
+      run: |
+        pip install black
+        black .
+
+    - name: Test with pytest
       env:
         FIREBASE_CRED_PATH: ${{ env.FIREBASE_CRED_PATH }}
         FIREBASE_DATABASE_URL: ${{ env.FIREBASE_DATABASE_URL }}
       run: |
         pip install pytest
-        pytest --tb=short -v
+        pytest
+
+
+
+    # - name: Lint with flake8
+    #   run: |
+    #     pip install flake8
+    #     flake8 .
+
+    # - name: Check documentation with pydocstyle
+    #   run: |
+    #     pip install pydocstyle
+    #     pydocstyle .
+
