updated

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -7,114 +7,114 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - uses: actions/checkout@v2
+      - uses: actions/checkout@v2
 
-    - name: Set up Python 3.11
-      uses: actions/setup-python@v2
-      with:
-        python-version: 3.11
+      - name: Set up Python 3.11
+        uses: actions/setup-python@v2
+        with:
+          python-version: 3.11
 
-    - name: Install dependencies
-      run: |
-        python -m pip install --upgrade pip
-        pip install -r requirements.txt
-        pip install aiohttp
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install -r requirements.txt
+          pip install aiohttp
 
-    - name: Create Firebase Credentials File
-      run: |
-        #!/bin/bash
-        cat <<EOF >firebase_credentials.json
-        ${{ secrets.FIREBASE_CREDENTIALS_JSON }}
-        EOF
-      env:
-        FIREBASE_CREDENTIALS_JSON: ${{ secrets.FIREBASE_CREDENTIALS_JSON }}
+      - name: Create Firebase Credentials File
+        run: |
+          #!/bin/bash
+          cat <<EOF >firebase_credentials.json
+          ${{ secrets.FIREBASE_CREDENTIALS_JSON }}
+          EOF
+        env:
+          FIREBASE_CREDENTIALS_JSON: ${{ secrets.FIREBASE_CREDENTIALS_JSON }}
 
-    - name: Check Firebase Credentials File
-      run: cat ./firebase_credentials.json
+      - name: Check Firebase Credentials File
+        run: cat ./firebase_credentials.json
 
-    - name: Create ExpiryTrader Mock JSON
-      run: |
-        #!/bin/bash
-        cat <<EOF >ExpiryTrader_mock.json
-        ${{ secrets.EXPIRYTRADER_JSON }}
-        EOF
-      env:
-        EXPIRYTRADER_JSON: ${{ secrets.EXPIRYTRADER_JSON }}
+      - name: Create ExpiryTrader Mock JSON
+        run: |
+          #!/bin/bash
+          cat <<EOF >ExpiryTrader_mock.json
+          ${{ secrets.EXPIRYTRADER_JSON }}
+          EOF
+        env:
+          EXPIRYTRADER_JSON: ${{ secrets.EXPIRYTRADER_JSON }}
 
-    - name: Create FNO Info CSV File
-      run: |
-        #!/bin/bash
-        cat <<EOF >test_fno_info.csv
-        ${{ secrets.FNO_INFO_PATH }}
-        EOF
-      env:
-        FNO_INFO_PATH: ${{ secrets.FNO_INFO_PATH }}
+      - name: Create FNO Info CSV File
+        run: |
+          #!/bin/bash
+          cat <<EOF >test_fno_info.csv
+          ${{ secrets.FNO_INFO_PATH }}
+          EOF
+        env:
+          FNO_INFO_PATH: ${{ secrets.FNO_INFO_PATH }}
 
-    - name: Check FNO Info CSV File
-      run: cat ./test_fno_info.csv
+      - name: Check FNO Info CSV File
+        run: cat ./test_fno_info.csv
 
-    - name: Load environment variables
-      run: |
-        echo "FIREBASE_DATABASE_URL=${{ secrets.FIREBASE_DATABASE_URL }}" >> $GITHUB_ENV
-        echo "FIREBASE_CREDENTIALS_PATH=./firebase_credentials.json" >> $GITHUB_ENV
-        echo "FIREBASE_CRED_PATH=./firebase_credentials.json" >> $GITHUB_ENV
-        echo "FNO_INFO_PATH=./test_fno_info.csv" >> $GITHUB_ENV
-        echo "ZERODHA_BROKER=${{ secrets.ZERODHA_BROKER }}" >> $GITHUB_ENV
-        echo "ALICEBLUE_BROKER=${{ secrets.ALICEBLUE_BROKER }}" >> $GITHUB_ENV
-        echo "FIRSTOCK_BROKER=${{ secrets.FIRSTOCK_BROKER }}" >> $GITHUB_ENV
-        echo "FIREBASE_TEST_COLLECTION=${{ secrets.FIREBASE_TEST_COLLECTION }}" >> $GITHUB_ENV
-        echo "CONSOLIDATED_REPORT_PATH=./Data/ConsolidatedReports" >> $GITHUB_ENV
-        echo "ERROR_LOG_PATH=./Data/ErrorLogs/TradeManError.log" >> $GITHUB_ENV
-        echo "USER_SQLDB_PATH=./Data/UserSQLDB" >> $GITHUB_ENV
-        echo "FIREBASE_USER_COLLECTION=${{ secrets.FIREBASE_USER_COLLECTION }}" >> $GITHUB_ENV
+      - name: Load environment variables
+        run: |
+          echo "FIREBASE_DATABASE_URL=${{ secrets.FIREBASE_DATABASE_URL }}" >> $GITHUB_ENV
+          echo "FIREBASE_CREDENTIALS_PATH=./firebase_credentials.json" >> $GITHUB_ENV
+          echo "FIREBASE_CRED_PATH=./firebase_credentials.json" >> $GITHUB_ENV
+          echo "FNO_INFO_PATH=./test_fno_info.csv" >> $GITHUB_ENV
+          echo "ZERODHA_BROKER=${{ secrets.ZERODHA_BROKER }}" >> $GITHUB_ENV
+          echo "ALICEBLUE_BROKER=${{ secrets.ALICEBLUE_BROKER }}" >> $GITHUB_ENV
+          echo "FIRSTOCK_BROKER=${{ secrets.FIRSTOCK_BROKER }}" >> $GITHUB_ENV
+          echo "FIREBASE_TEST_COLLECTION=${{ secrets.FIREBASE_TEST_COLLECTION }}" >> $GITHUB_ENV
+          echo "CONSOLIDATED_REPORT_PATH=./Data/ConsolidatedReports" >> $GITHUB_ENV
+          echo "ERROR_LOG_PATH=./logs/TradeManError.log" >> $GITHUB_ENV
+          echo "USER_SQLDB_PATH=./Data/UserSQLDB" >> $GITHUB_ENV
+          echo "FIREBASE_USER_COLLECTION=${{ secrets.FIREBASE_USER_COLLECTION }}" >> $GITHUB_ENV
 
-    - name: Verify environment variables
-      run: |
-        echo "Verifying environment variables..."
-        echo "ERROR_LOG_PATH is set to $ERROR_LOG_PATH"
-        if [ -z "$ERROR_LOG_PATH" ]; then
-          echo "ERROR_LOG_PATH is not set!"
-          exit 1
-        fi
+      - name: Verify environment variables
+        run: |
+          echo "Verifying environment variables..."
+          echo "ERROR_LOG_PATH is set to $ERROR_LOG_PATH"
+          if [ -z "$ERROR_LOG_PATH" ]; then
+            echo "ERROR_LOG_PATH is not set!"
+            exit 1
+          fi
 
-    - name: Verify directory structure and permissions
-      run: |
-        echo "Verifying directory structure and permissions..."
-        ls -al ./Data/ErrorLogs/
-        echo "Checking log file permissions..."
-        ls -l ./Data/ErrorLogs/TradeManError.log
+      - name: Verify directory structure and permissions
+        run: |
+          echo "Verifying directory structure and permissions..."
+          ls -al ./logs/
+          echo "Checking log file permissions..."
+          ls -l ./logs/TradeManError.log
 
-    - name: Create logs directory
-      run: |
-        mkdir -p ./logs/
-        echo "Logs directory created at $(pwd)/logs/"
+      - name: Create logs directory
+        run: |
+          mkdir -p ./logs/
+          echo "Logs directory created at $(pwd)/logs/"
 
-    - name: Check formatting with black
-      run: |
-        pip install black
-        black .
+      - name: Check formatting with black
+        run: |
+          pip install black
+          black .
 
-    # Uncomment and use as needed:
-    # - name: Lint with flake8
-    #   run: |
-    #     pip install flake8
-    #     flake8 .
+      # Uncomment and use as needed:
+      # - name: Lint with flake8
+      #   run: |
+      #     pip install flake8
+      #     flake8 .
 
-    # - name: Check documentation with pydocstyle
-    #   run: |
-    #     pip install pydocstyle
-    #     pydocstyle .
+      # - name: Check documentation with pydocstyle
+      #   run: |
+      #     pip install pydocstyle
+      #     pydocstyle .
 
-    - name: Test with pytest
-      run: |
-        pip install pytest
-        pytest
+      - name: Test with pytest
+        run: |
+          pip install pytest
+          pytest
 
-    - name: Upload Log Files
-      uses: actions/upload-artifact@v2
-      with:
-        name: Logs
-        path: ./Data/ErrorLogs/TradeManError.log
+      - name: Upload Log Files
+        uses: actions/upload-artifact@v2
+        with:
+          name: Logs
+          path: ./logs/TradeManError.log
 
-    - name: List files in TestData directory
-      run: ls -l path/to/TestData
+      - name: List files in TestData directory
+        run: ls -l path/to/TestData
