Update python-app.yml

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -13,7 +13,7 @@ jobs:
     - name: Set up Python 3.11
       uses: actions/setup-python@v2
       with:
-        python-version: 3.11
+        python-version: '3.11'
 
     - name: Install dependencies
       run: |
@@ -21,12 +21,26 @@ jobs:
         pip install -r requirements.txt
 
     - name: Set up Firebase credentials
-      run: |
-        echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_BASE64 }}" | base64 --decode > firebase-service-account.json
+      # Write the JSON content from the secret to a file
+      run: echo "${{ secrets.FIREBASE_CRED_PATH }}" > firebase-service-account.json
       shell: bash
 
-    - name: Export Firebase database URL
-      run: echo "FIREBASE_DATABASE_URL=${{ secrets.FIREBASE_DATABASE_URL }}" >> $GITHUB_ENV
+    - name: Export Firebase environment variables
+      # Set the environment variables for the database URL and credentials path
+      run: |
+        echo "FIREBASE_CRED_PATH=$(pwd)/firebase-service-account.json" >> $GITHUB_ENV
+        echo "FIREBASE_DATABASE_URL=${{ secrets.FIREBASE_DATABASE_URL }}" >> $GITHUB_ENV
+      shell: bash
+
+    - name: Verify Firebase credentials
+      run: |
+        if [ -f "$FIREBASE_CRED_PATH" ]; then
+          echo "Firebase credentials file found at $FIREBASE_CRED_PATH"
+          cat $FIREBASE_CRED_PATH
+        else
+          echo "Firebase credentials file not found."
+          exit 1
+        fi
       shell: bash
 
     - name: Check formatting with black
@@ -36,11 +50,12 @@ jobs:
 
     - name: Test with pytest
       env:
-        FIREBASE_CRED_PATH: ${{ secrets.FIREBASE_CRED_PATH }}
-        FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
+        FIREBASE_CRED_PATH: ${{ env.FIREBASE_CRED_PATH }}
+        FIREBASE_DATABASE_URL: ${{ env.FIREBASE_DATABASE_URL }}
       run: |
         pip install pytest
         pytest
+
 
 
     # - name: Lint with flake8
